type Query {
	people: [Person!]!
	latestTweets: [Tweet!]!
}

type Mutation {
	addPerson(name: String!, age: Int!, isAdult: Boolean!, bio: String): Person!
	addTweet(description: String!, person: ID!): Tweet!
	deleteTweet(tweet: ID!): Tweet
}

type Subscription {
	tweetAdded: Tweet
}

type Tweet {
	_id: ID!
	description: String!
	likes: Int!
	person: Person!
}

type Person {
	id: ID!
	name: String!
	age: Int!
	isAdult: Boolean!
	bio: String
	tweets: [Tweet!]!
}